for path in ([[sound/gmodtower/inventory/move_paper.wav
sound/gmodtower/lobby/instruments/piano/a30.wav
sound/gmodtower/lobby/instruments/piano/b20.wav
sound/gmodtower/lobby/instruments/piano/a20.wav
sound/gmodtower/lobby/instruments/piano/a15.wav
sound/gmodtower/lobby/instruments/piano/b8.wav
sound/gmodtower/lobby/instruments/piano/a23.wav
sound/gmodtower/lobby/instruments/piano/a5.wav
sound/gmodtower/lobby/instruments/piano/b3.wav
sound/gmodtower/lobby/instruments/piano/a36.wav
sound/gmodtower/lobby/instruments/piano/b2.wav
sound/gmodtower/lobby/instruments/piano/a11.wav
sound/gmodtower/lobby/instruments/piano/a9.wav
sound/gmodtower/lobby/instruments/piano/a24.wav
sound/gmodtower/lobby/instruments/piano/a12.wav
sound/gmodtower/lobby/instruments/piano/b5.wav
sound/gmodtower/lobby/instruments/piano/a19.wav
sound/gmodtower/lobby/instruments/piano/b16.wav
sound/gmodtower/lobby/instruments/piano/b23.wav
sound/gmodtower/lobby/instruments/piano/a14.wav
sound/gmodtower/lobby/instruments/piano/a17.wav
sound/gmodtower/lobby/instruments/piano/a25.wav
sound/gmodtower/lobby/instruments/piano/a13.wav
sound/gmodtower/lobby/instruments/piano/a28.wav
sound/gmodtower/lobby/instruments/piano/a22.wav
sound/gmodtower/lobby/instruments/piano/a33.wav
sound/gmodtower/lobby/instruments/piano/b24.wav
sound/gmodtower/lobby/instruments/piano/a2.wav
sound/gmodtower/lobby/instruments/piano/a35.wav
sound/gmodtower/lobby/instruments/piano/a16.wav
sound/gmodtower/lobby/instruments/piano/b21.wav
sound/gmodtower/lobby/instruments/piano/a8.wav
sound/gmodtower/lobby/instruments/piano/a27.wav
sound/gmodtower/lobby/instruments/piano/b7.wav
sound/gmodtower/lobby/instruments/piano/a1.wav
sound/gmodtower/lobby/instruments/piano/a10.wav
sound/gmodtower/lobby/instruments/piano/b14.wav
sound/gmodtower/lobby/instruments/piano/a4.wav
sound/gmodtower/lobby/instruments/piano/a6.wav
sound/gmodtower/lobby/instruments/piano/a34.wav
sound/gmodtower/lobby/instruments/piano/a26.wav
sound/gmodtower/lobby/instruments/piano/b12.wav
sound/gmodtower/lobby/instruments/piano/a18.wav
sound/gmodtower/lobby/instruments/piano/b6.wav
sound/gmodtower/lobby/instruments/piano/b15.wav
sound/gmodtower/lobby/instruments/piano/b18.wav
sound/gmodtower/lobby/instruments/piano/b4.wav
sound/gmodtower/lobby/instruments/piano/b22.wav
sound/gmodtower/lobby/instruments/piano/a21.wav
sound/gmodtower/lobby/instruments/piano/a31.wav
sound/gmodtower/lobby/instruments/piano/a7.wav
sound/gmodtower/lobby/instruments/piano/a29.wav
sound/gmodtower/lobby/instruments/piano/b17.wav
sound/gmodtower/lobby/instruments/piano/a32.wav
sound/gmodtower/lobby/instruments/piano/b25.wav
sound/gmodtower/lobby/instruments/piano/b1.wav
sound/gmodtower/lobby/instruments/piano/b10.wav
sound/gmodtower/lobby/instruments/piano/b9.wav
sound/gmodtower/lobby/instruments/piano/b13.wav
sound/gmodtower/lobby/instruments/piano/b11.wav
sound/gmodtower/lobby/instruments/piano/b19.wav
sound/gmodtower/lobby/instruments/piano/a3.wav
materials/sprites/music.vmt
materials/sprites/music.vtf
materials/vgui/entities/gmt_instrument_piano.vtf
materials/vgui/entities/gmt_instrument_piano.vmt
materials/gmod_tower/instruments/piano/piano_large.vmt
materials/gmod_tower/instruments/piano/piano_note_right.vtf
materials/gmod_tower/instruments/piano/piano_note_full.vtf
materials/gmod_tower/instruments/piano/piano_large.vtf
materials/gmod_tower/instruments/piano/piano_note_left.vtf
materials/gmod_tower/instruments/piano/piano_note_left.vmt
materials/gmod_tower/instruments/piano/piano_note_middle.vtf
materials/gmod_tower/instruments/piano/piano.vtf
materials/gmod_tower/instruments/piano/piano_note_right.vmt
materials/gmod_tower/instruments/piano/piano_note_top.vtf
materials/gmod_tower/instruments/piano/piano_note_rightmid.vtf
materials/gmod_tower/instruments/piano/piano_note_top.vmt
materials/gmod_tower/instruments/piano/piano.vmt
materials/gmod_tower/instruments/piano/piano_note_leftmid.vtf
materials/gmod_tower/instruments/piano/piano_note_rightmid.vmt
materials/gmod_tower/instruments/piano/piano_note_middle.vmt
materials/gmod_tower/instruments/piano/piano_note_leftmid.vmt
materials/gmod_tower/instruments/piano/piano_note_full.vmt
models/fishy/furniture/piano_seat.sw.vtx
models/fishy/furniture/piano.dx90.vtx
models/fishy/furniture/piano.dx80.vtx
models/fishy/furniture/piano_seat.mdl
models/fishy/furniture/piano.mdl
models/fishy/furniture/piano_seat.dx90.vtx
models/fishy/furniture/piano_seat.dx80.vtx
models/fishy/furniture/piano.sw.vtx
models/fishy/furniture/piano.vvd
models/fishy/furniture/piano_seat.vvd
models/fishy/furniture/piano.phy
models/fishy/furniture/piano_seat.phy]]):gmatch'[^\r\n]+' 
do
	resource.AddSingleFile(path)
end